<script lang="ts">
	let { data, form } = $props();
	const labels: Record<string, string> = { project: 'Project', team_contest: 'Team Contest', topical_team: 'Topical Team', topical_individual: 'Topical Individual', knowdown: 'Knowdown' };
</script>

<svelte:head><title>{data.season.name} qualifications — WSMC</title></svelte:head>
<main><p><a href="/program">← Program</a></p><h1>{data.season.name} qualifications</h1><p>Generate explainable regional placement qualifiers after finalization, review every reason, then publish the frozen round.</p>
	{#if form?.error}<p class="error" role="alert">{form.error}</p>{/if}{#if form?.success}<p class="success" role="status">{form.success}</p>{/if}
	<section><h2>Generate from a finalized regional</h2><form method="POST" action="?/generate"><label>Regional contest <select name="contestId" required>{#each data.contests as contest}<option value={contest.id} disabled={contest.lifecycle !== 'finalized'}>{contest.name} · {contest.lifecycle}</option>{/each}</select></label><button type="submit">Generate qualification draft</button></form><p class="hint">Generation is idempotent while the round is a draft. Once published, reasons are frozen.</p></section>
	<section><h2>Regional placement round</h2>{#if data.review.round}<p class="status">{data.review.round.status}{#if data.review.round.publishedAt} · published{/if} · {data.review.qualifications.length} qualified entries/alternates</p>{#if data.review.qualifications.length}<table><thead><tr><th>Category</th><th>School</th><th>Entry</th><th>Student</th><th>Active</th><th>Reasons</th></tr></thead><tbody>{#each data.review.qualifications as qualification}<tr><td>{labels[qualification.category] ?? qualification.category}</td><td>{qualification.schoolName}</td><td>{qualification.entryNumber ?? '—'}</td><td>{qualification.studentName ?? 'Team entry'}</td><td>{qualification.active ? 'Yes' : 'Alternate'}</td><td>{qualification.reasons.map((reason) => `${reason.kind}${reason.scope ? ` · ${reason.scope}` : ''}${reason.rank ? ` · rank ${reason.rank}` : ''}`).join('; ')}</td></tr>{/each}</tbody></table>{:else}<p>No placement decisions have been generated.</p>{/if}{#if data.review.round.status === 'draft'}<form method="POST" action="?/publish"><button type="submit" disabled={!data.review.qualifications.length}>Publish and freeze this round</button></form>{/if}{:else}<p>No regional placement round yet.</p>{/if}</section>
</main>
<style>
	main { max-width: 1100px; margin: 0 auto; padding: 1rem; overflow-wrap: anywhere; } h1 { margin-bottom: .25rem; } section { margin-top: 1.5rem; border-top: 1px solid #ddd; padding-top: 1rem; } form { display: flex; flex-wrap: wrap; align-items: end; gap: .7rem; } label { display: flex; flex-direction: column; gap: .2rem; font-weight: 600; } select, button { min-height: 2.75rem; padding: .55rem; font: inherit; } button { border: 0; border-radius: 4px; background: #1a1a2e; color: #fff; cursor: pointer; } button:disabled { opacity: .5; } table { width: 100%; border-collapse: collapse; margin-top: 1rem; } th, td { padding: .55rem; border-bottom: 1px solid #eee; text-align: left; vertical-align: top; } th { background: #f5f7fb; } .status, .hint { color: #566; } .error, .success { padding: .7rem; border-radius: 5px; } .error { background: #fbe3e3; color: #9a2020; } .success { background: #e2f5e8; color: #176b35; } @media (max-width: 700px) { form { align-items: stretch; flex-direction: column; } table { display: block; overflow-x: auto; white-space: nowrap; } }
</style>
